apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-sdk-apicurio-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-sdk-apicurio-registry
    app.kubernetes.io/part-of: apicurio-registry
  name: python-sdk-apicurio-registry
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-sdk-apicurio-registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-sdk-apicurio-registry
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/riprasad-tenant/apicurio-registry/python-sdk-apicurio-registry@sha256:3c3186b838fda298ee9d158b422d88f53603f484edf6580a0170918887a23dd0
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
