apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-sdk-apicurio-registry
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/riprasad-tenant/apicurio-registry/python-sdk-apicurio-registry@sha256:3c3186b838fda298ee9d158b422d88f53603f484edf6580a0170918887a23dd0
        name: my-python
        resources: {}
status: {}
